# Site settings
name: Louie Han
description: ""
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
#codepen_username: your_codepen_username_goes_here
facebook_username: louiehan1015
#vk_username: your_vk_username_goes_here
twitter_username: Louiehan1015
#google_plus_username: your_google_plus_username_goes_here
#linkedin_username: your_linked_in_username_goes_here
#vine_username:  your_vine_username_goes_here
instagram_username:  louiehan
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
tumblr_username: louiehan
weibo_username: louieh
#lastfm_username: your_lastfm_username_goes_here
#blog_url: "/blog"
github_username:  louieh
email: louie.han.work@gmail.com
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: no
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/IMG_3207.JPG"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
